#!/usr/bin/env bash
# otta-codex-setup.sh <owner/repo> <pulse-token>
#
# Wires Codex CLI telemetry to Otta Pulse by merging an [otel] block into
# ~/.codex/config.toml (or $CODEX_HOME/config.toml).
#
# Codex reads OTEL config from config.toml only — it does NOT honor OTEL_* env
# vars. This script merges only the [otel] and [otel.*] sections, preserving all
# other config.toml content verbatim.
#
# Also writes .otta/codex.env (legacy, backward compat — Codex does not read
# these env vars, but kept for documentation / tooling that sources the file).
#
# Endpoint base: OTTA_PULSE_URL if set, else the hosted default.
set -euo pipefail

REPO="${1:-}"
TOKEN="${2:-}"

if [ -z "$REPO" ] || [ -z "$TOKEN" ]; then
  echo "usage: otta-codex-setup.sh <owner/repo> <pulse-token>" >&2
  exit 2
fi

command -v python3 >/dev/null 2>&1 || { echo "ERROR: python3 required." >&2; exit 1; }

PULSE="${OTTA_PULSE_URL:-https://pulse.otta.build}"
PULSE="${PULSE%/}"  # normalize trailing slash

# ---------------------------------------------------------------------------
# 1. Merge [otel] block into $CODEX_HOME/config.toml (or ~/.codex/config.toml)
# ---------------------------------------------------------------------------
CODEX_DIR="${CODEX_HOME:-$HOME/.codex}"
mkdir -p "$CODEX_DIR"
CONFIG_TOML="$CODEX_DIR/config.toml"

OTTA_PULSE="$PULSE" OTTA_TOKEN="$TOKEN" python3 - "$CONFIG_TOML" <<'PY'
import sys, os

path = sys.argv[1]
pulse = os.environ["OTTA_PULSE"]
token = os.environ["OTTA_TOKEN"]

# Read existing content (or start empty)
try:
    with open(path) as f:
        lines = f.readlines()
except FileNotFoundError:
    lines = []

# Strip only [otel.exporter.otlp-http] and [otel.exporter.otlp-http.headers]
# sections. The [otel] direct-key section is preserved (AC2).
kept = []
has_otel = False
in_otlp = False
for line in lines:
    stripped = line.strip()
    if stripped.startswith('['):
        if stripped == '[otel]':
            has_otel = True
        # Only skip the two otlp-http sub-sections
        in_otlp = stripped.startswith('[otel.exporter.otlp-http')
    if not in_otlp:
        kept.append(line)

# Remove trailing blank lines from preserved content
content = ''.join(kept).rstrip('\n')

# Exporter sub-sections only (token-bearing; always overwritten)
exporter_block = (
    '[otel.exporter.otlp-http]\n'
    'endpoint = "' + pulse + '"\n'
    'protocol = "json"\n'
    '\n'
    '[otel.exporter.otlp-http.headers]\n'
    'x-pulse-token = "' + token + '"\n'
)

# Default [otel] header written only when absent from existing config
otel_header = (
    '[otel]\n'
    'log_user_prompt = false\n'
    'environment = "production"\n'
)

if content:
    if has_otel:
        # Existing [otel] section present — just append exporter sub-sections
        final = content + '\n\n' + exporter_block
    else:
        # No [otel] section — add defaults then exporter
        final = content + '\n\n' + otel_header + '\n' + exporter_block
else:
    if has_otel:
        # File had only otel sections (all stripped) — just write exporter
        final = exporter_block
    else:
        final = otel_header + '\n' + exporter_block

with open(path, 'w') as f:
    f.write(final)
PY

chmod 600 "$CONFIG_TOML"

# ---------------------------------------------------------------------------
# 2. Write .otta/codex.env — LEGACY: Codex does not read these env vars.
#    Kept for backward compat and documentation only.
# ---------------------------------------------------------------------------
ENV_FILE=".otta/codex.env"
mkdir -p ".otta"

cat > "$ENV_FILE" <<ENV
# LEGACY — Codex does not read these env vars. Use ~/.codex/config.toml instead.
# This file is kept for backward compatibility only. See config.toml for the
# active telemetry configuration written by otta-codex-setup.
#
# Generated by otta-codex-setup — do NOT commit (token-bearing)
export OTEL_LOGS_EXPORTER=otlp
export OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=${PULSE}/v1/logs
export OTEL_EXPORTER_OTLP_LOGS_HEADERS=x-pulse-token=${TOKEN}
export OTEL_EXPORTER_OTLP_LOGS_PROTOCOL=http/json
export OTEL_METRICS_EXPORTER=otlp
export OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=${PULSE}/v1/metrics
export OTEL_EXPORTER_OTLP_METRICS_HEADERS=x-pulse-token=${TOKEN}
export OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=http/json
export OTEL_RESOURCE_ATTRIBUTES=repo=${REPO},harness=codex
ENV

chmod 600 "$ENV_FILE"

# Ensure .otta/codex.env is gitignored (token-bearing)
if [ -f .gitignore ]; then
  grep -qxF '.otta/codex.env' .gitignore || printf '\n.otta/codex.env\n' >> .gitignore
else
  printf '.otta/codex.env\n' > .gitignore
fi

echo "Telemetry wired (Codex → Pulse) — written to ${CONFIG_TOML}."
echo "Data will be sent to pulse.otta.build (hosted by Otta). Set OTTA_PULSE_URL to override."
echo ""
echo "Codex reads OTEL config from config.toml — no further setup needed."
echo "Legacy env file also written to ${ENV_FILE} (gitignored, Codex does not read it)."
