#!/usr/bin/env bash
# otta-codex-setup.sh <owner/repo> <pulse-token>
#
# Writes .otta/codex.env with standard OTEL env vars for Codex CLI telemetry.
# Source before each Codex session: source .otta/codex.env
#
# Uses standard OTEL_* env vars — Codex inherits these from the environment.
# Endpoint base: OTTA_PULSE_URL if set, else the hosted default.
#
# NOTE: Integration requires that your Codex version forwards OTEL_* env vars
# to its telemetry pipeline. Verify against your Codex version if telemetry
# does not appear in Otta Pulse.
set -euo pipefail

REPO="${1:-}"
TOKEN="${2:-}"

if [ -z "$REPO" ] || [ -z "$TOKEN" ]; then
  echo "usage: otta-codex-setup.sh <owner/repo> <pulse-token>" >&2
  exit 2
fi

PULSE="${OTTA_PULSE_URL:-https://pulse.otta.build}"
PULSE="${PULSE%/}"  # normalize trailing slash

ENV_FILE=".otta/codex.env"
mkdir -p ".otta"

cat > "$ENV_FILE" <<ENV
# Otta Pulse telemetry for Codex CLI — source before each session
# Generated by otta-codex-setup — do NOT commit (token-bearing)
# Standard OTEL env vars; verify forwarding against your Codex version.
export OTEL_LOGS_EXPORTER=otlp
export OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=${PULSE}/v1/logs
export OTEL_EXPORTER_OTLP_LOGS_HEADERS=x-pulse-token=${TOKEN}
export OTEL_EXPORTER_OTLP_LOGS_PROTOCOL=http/json
export OTEL_METRICS_EXPORTER=otlp
export OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=${PULSE}/v1/metrics
export OTEL_EXPORTER_OTLP_METRICS_HEADERS=x-pulse-token=${TOKEN}
export OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=http/json
export OTEL_RESOURCE_ATTRIBUTES=repo=${REPO},harness=codex
ENV

chmod 600 "$ENV_FILE"

# Ensure .otta/codex.env is gitignored (token-bearing)
if [ -f .gitignore ]; then
  grep -qxF '.otta/codex.env' .gitignore || printf '\n.otta/codex.env\n' >> .gitignore
else
  printf '.otta/codex.env\n' > .gitignore
fi

echo "Telemetry wired (Codex → Pulse logs + metrics) — written to ${ENV_FILE} (gitignored)."
echo "Data will be sent to pulse.otta.build (hosted by Otta). Set OTTA_PULSE_URL to override."
echo ""
echo "To activate, source before each Codex session:"
echo "  source ${ENV_FILE}"
